main: ledennis.mypluginmanager.MyPluginManager

name: myPluginManager
author: LeDennis32
version: 2.0
description: Plugin for managing your plugins.

commands:
  pm:
    description: Main command
    usage: See /<command>
    permission: pm.basic